FROM python:3.9.17-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt --no-cache-dir

COPY src /app/
COPY data /app/data/

CMD ["python", "-u", "/app/stock_market_producer.py"]
